options:
  source:
    type: string
    default: dev
    description: |
      Location and packages to install hadoop:
      .
       * dev:     Install using the hadoop packages from
                  ppa:hadoop-ubuntu/dev.
       * testing: Install using the hadoop packages from
                  ppa:hadoop-ubuntu/testing.
       * stable:  Install using the hadoop packages from
                  ppa:hadoop-ubuntu/stable.
      .
      The packages provides in the hadoop-ubuntu team PPA's are based
      directly on upstream hadoop releases but are not fully built from
      source.
  hbase:
    type: string
    default: false
    description: |
      Setting this configuration parameter to 'true' configures HDFS for
      use with HBase including turning on 'append' mode which is not
      desirable in all deployment scenarios.
